import React, { useState, useEffect, useRef } from "react";
import type { ReactNode } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import { Input } from "@/components/ui/input";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Separator } from "@/components/ui/separator";
import { Dialog, DialogContent, DialogTrigger, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Slider } from "@/components/ui/slider";

/* ═══ ICONS ═══ */
const I:Record<string,(p?:any)=>React.ReactElement> = {
  Globe:(p:any={})=><svg {...p} width={p.size||18} height={p.size||18} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="10"/><path d="M12 2a14.5 14.5 0 0 0 0 20 14.5 14.5 0 0 0 0-20"/><path d="M2 12h20"/></svg>,
  Users:(p:any={})=><svg {...p} width={p.size||16} height={p.size||16} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/></svg>,
  TrendUp:(p:any={})=><svg {...p} width={p.size||16} height={p.size||16} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polyline points="22 7 13.5 15.5 8.5 10.5 2 17"/><polyline points="16 7 22 7 22 13"/></svg>,
  Shield:(p:any={})=><svg {...p} width={p.size||16} height={p.size||16} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z"/></svg>,
  Zap:(p:any={})=><svg {...p} width={p.size||16} height={p.size||16} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 14a1 1 0 0 1-.78-1.63l9.9-10.2a.5.5 0 0 1 .86.46l-1.92 6.02A1 1 0 0 0 13 10h7a1 1 0 0 1 .78 1.63l-9.9 10.2a.5.5 0 0 1-.86-.46l1.92-6.02A1 1 0 0 0 11 14z"/></svg>,
  Brain:(p:any={})=><svg {...p} width={p.size||16} height={p.size||16} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 5a3 3 0 1 0-5.997.125 4 4 0 0 0-2.526 5.77 4 4 0 0 0 .556 6.588A4 4 0 1 0 12 18Z"/><path d="M12 5a3 3 0 1 1 5.997.125 4 4 0 0 1 2.526 5.77 4 4 0 0 1-.556 6.588A4 4 0 1 1 12 18Z"/></svg>,
  Heart:(p:any={})=><svg {...p} width={p.size||16} height={p.size||16} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M19 14c1.49-1.46 3-3.21 3-5.5A5.5 5.5 0 0 0 16.5 3c-1.76 0-3 .5-4.5 2-1.5-1.5-2.74-2-4.5-2A5.5 5.5 0 0 0 2 8.5c0 2.3 1.5 4.05 3 5.5l7 7Z"/></svg>,
  Check:(p:any={})=><svg {...p} width={p.size||14} height={p.size||14} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"/><path d="m9 11 3 3L22 4"/></svg>,
  Alert:(p:any={})=><svg {...p} width={p.size||14} height={p.size||14} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3"/><path d="M12 9v4"/><path d="M12 17h.01"/></svg>,
  Bar:(p:any={})=><svg {...p} width={p.size||16} height={p.size||16} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><line x1="12" x2="12" y1="20" y2="10"/><line x1="18" x2="18" y1="20" y2="4"/><line x1="6" x2="6" y1="20" y2="16"/></svg>,
  Send:(p:any={})=><svg {...p} width={p.size||16} height={p.size||16} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M14.536 21.686a.5.5 0 0 0 .937-.024l6.5-19a.496.496 0 0 0-.635-.635l-19 6.5a.5.5 0 0 0-.024.937l7.93 3.18a2 2 0 0 1 1.112 1.11z"/></svg>,
  ChevR:(p:any={})=><svg {...p} width={p.size||14} height={p.size||14} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m9 18 6-6-6-6"/></svg>,
  Layers:(p:any={})=><svg {...p} width={p.size||16} height={p.size||16} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m12.83 2.18a2 2 0 0 0-1.66 0L2.6 6.08a1 1 0 0 0 0 1.83l8.58 3.91a2 2 0 0 0 1.66 0l8.58-3.9a1 1 0 0 0 0-1.83Z"/><path d="m22 17.65-9.17 4.16a2 2 0 0 1-1.66 0L2 17.65"/><path d="m22 12.65-9.17 4.16a2 2 0 0 1-1.66 0L2 12.65"/></svg>,
  Dollar:(p:any={})=><svg {...p} width={p.size||16} height={p.size||16} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><line x1="12" x2="12" y1="2" y2="22"/><path d="M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6"/></svg>,
  GitBranch:(p:any={})=><svg {...p} width={p.size||16} height={p.size||16} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><line x1="6" x2="6" y1="3" y2="15"/><circle cx="18" cy="6" r="3"/><circle cx="6" cy="18" r="3"/><path d="M18 9a9 9 0 0 1-9 9"/></svg>,
  Msg:(p:any={})=><svg {...p} width={p.size||16} height={p.size||16} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M7.9 20A9 9 0 1 0 4 16.1L2 22Z"/></svg>,
  Map:(p:any={})=><svg {...p} width={p.size||16} height={p.size||16} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M14.106 5.553a2 2 0 0 0 1.788 0l3.659-1.83A1 1 0 0 1 21 4.619v12.764a1 1 0 0 1-.553.894l-4.553 2.277a2 2 0 0 1-1.788 0l-4.212-2.106a2 2 0 0 0-1.788 0l-3.659 1.83A1 1 0 0 1 3 19.381V6.618a1 1 0 0 1 .553-.894l4.553-2.277a2 2 0 0 1 1.788 0z"/><path d="M15 5.764v15"/><path d="M9 3.236v15"/></svg>,
  BookOpen:(p:any={})=><svg {...p} width={p.size||16} height={p.size||16} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 7v14"/><path d="M3 18a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1h5a4 4 0 0 1 4 4 4 4 0 0 1 4-4h5a1 1 0 0 1 1 1v13a1 1 0 0 1-1 1h-6a3 3 0 0 0-3 3 3 3 0 0 0-3-3z"/></svg>,
  Route:(p:any={})=><svg {...p} width={p.size||16} height={p.size||16} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="6" cy="19" r="3"/><path d="M9 19h8.5a3.5 3.5 0 0 0 0-7h-11a3.5 3.5 0 0 1 0-7H15"/><circle cx="18" cy="5" r="3"/></svg>,
  Activity:(p:any={})=><svg {...p} width={p.size||16} height={p.size||16} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M22 12h-2.48a2 2 0 0 0-1.93 1.46l-2.35 8.36a.25.25 0 0 1-.48 0L9.24 2.18a.25.25 0 0 0-.48 0l-2.35 8.36A2 2 0 0 1 4.49 12H2"/></svg>,
};

/* ═══ PRIMITIVES ═══ */
function Spark({data,color,w=100,h=28}:{data:number[];color:string;w?:number;h?:number}){const mx=Math.max(...data),mn=Math.min(...data),r=mx-mn||1;const pts=data.map((v,i)=>`${(i/(data.length-1))*w},${h-((v-mn)/r)*h}`).join(" ");return<svg width={w} height={h} className="overflow-visible"><polyline points={pts} fill="none" stroke={color} strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/><circle cx={w} cy={h-((data[data.length-1]-mn)/r)*h} r="2.5" fill={color}/></svg>;}
function Dot({s}:{s:"on"|"warn"|"crit"|"off"}){const c={on:"bg-emerald-400",warn:"bg-amber-400",crit:"bg-red-400",off:"bg-slate-500"};return<span className="relative flex h-2 w-2">{s==="on"&&<span className={`animate-ping absolute inline-flex h-full w-full rounded-full ${c[s]} opacity-75`}/>}<span className={`relative inline-flex rounded-full h-2 w-2 ${c[s]}`}/></span>;}

function DrillCard({title,value,unit,change,spark,color,icon,children}:{title:string;value:string;unit?:string;change:number;spark:number[];color:string;icon:ReactNode;children:ReactNode}){
  const[open,setOpen]=useState(false);
  return(<Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild>
    <div className="group relative bg-[#0f1923] border border-[#1e2d3d] rounded-lg p-4 hover:border-[#2a4a6b] transition-all cursor-pointer overflow-hidden">
      <div className="absolute inset-0 opacity-0 group-hover:opacity-100 transition-opacity" style={{background:`radial-gradient(ellipse at 50% 0%,${color}08 0%,transparent 70%)`}}/>
      <div className="relative z-10">
        <div className="flex items-start justify-between mb-2"><div className="flex items-center gap-2"><span className="opacity-60">{icon}</span><span className="text-[10px] uppercase tracking-[0.1em] text-[#6b8aad] font-medium">{title}</span></div><div className={`flex items-center gap-1 text-[10px] font-medium ${change>=0?"text-emerald-400":"text-red-400"}`}><span>{change>=0?"\u2191":"\u2193"}</span>{Math.abs(change)}%</div></div>
        <div className="flex items-end justify-between"><div><div className="text-xl font-semibold text-[#e8f0f8]">{value}<span className="text-xs text-[#6b8aad] ml-1">{unit}</span></div></div><Spark data={spark} color={color}/></div>
        <div className="text-[10px] text-[#3a5a7a] mt-1 flex items-center gap-1">Click to drill down <I.ChevR/></div>
      </div>
    </div>
  </DialogTrigger><DialogContent className="bg-[#0a1218] border-[#1e2d3d] text-[#c8dff0] max-w-3xl max-h-[80vh] overflow-y-auto"><DialogHeader><DialogTitle className="text-[#e8f0f8] flex items-center gap-2">{icon} {title}</DialogTitle></DialogHeader>{children}</DialogContent></Dialog>);
}

function DrillRow({label,children}:{label:string;children:ReactNode}){const[open,setOpen]=useState(false);return(<div className="border-b border-[#162535] last:border-0"><button onClick={()=>setOpen(!open)} className="w-full flex items-center gap-3 py-2.5 text-xs text-[#a8c8e0] hover:text-[#e8f0f8] transition-colors"><I.ChevR className={`transition-transform shrink-0 ${open?"rotate-90":""}`}/><span className="flex-1 text-left">{label}</span></button>{open&&<div className="pl-7 pb-3 text-[11px] text-[#6b8aad] space-y-2 animate-in fade-in slide-in-from-top-1 duration-200">{children}</div>}</div>);}

/* ═══ DATA ═══ */
const topLangs=[{lang:"Spanish",pct:62,enc:"1.76M",c:"#3a7abd",inPerson:68,vri:22,opi:10,cost:1.12},{lang:"Mandarin",pct:8,enc:"228K",c:"#10b981",inPerson:42,vri:38,opi:20,cost:1.68},{lang:"Arabic",pct:5,enc:"142K",c:"#f59e0b",inPerson:35,vri:40,opi:25,cost:1.82},{lang:"Vietnamese",pct:4,enc:"114K",c:"#8b5cf6",inPerson:38,vri:35,opi:27,cost:1.74},{lang:"ASL",pct:3.5,enc:"100K",c:"#ec4899",inPerson:55,vri:45,opi:0,cost:2.10},{lang:"Hmong",pct:2.8,enc:"80K",c:"#06b6d4",inPerson:30,vri:28,opi:42,cost:1.95},{lang:"Burmese",pct:2.2,enc:"63K",c:"#14b8a6",inPerson:25,vri:30,opi:45,cost:2.15},{lang:"Swahili",pct:1.8,enc:"51K",c:"#a855f7",inPerson:20,vri:25,opi:55,cost:2.28}];

const regions=[{r:"Illinois",fill:72,vol:"1.2M",s:"on" as const,lep:"412K",growth:3.2,interpreters:62,costPerMin:1.18,satisfaction:95.1},{r:"Wisconsin",fill:65,vol:"380K",s:"on" as const,lep:"189K",growth:4.8,interpreters:28,costPerMin:1.32,satisfaction:93.4},{r:"North Carolina",fill:61,vol:"520K",s:"warn" as const,lep:"298K",growth:8.1,interpreters:34,costPerMin:1.48,satisfaction:90.2},{r:"South Carolina",fill:58,vol:"210K",s:"warn" as const,lep:"142K",growth:9.4,interpreters:14,costPerMin:1.62,satisfaction:88.1},{r:"Georgia",fill:55,vol:"340K",s:"warn" as const,lep:"267K",growth:11.2,interpreters:18,costPerMin:1.55,satisfaction:87.4},{r:"Alabama",fill:52,vol:"198K",s:"crit" as const,lep:"98K",growth:12.4,interpreters:8,costPerMin:1.78,satisfaction:84.2}];

const censusData={totalLEP:"1.82M",projected5yr:"2.34M",growthRate:28.6,growthLangs:[{lang:"Arabic",growth:34.2,drivers:"Refugee resettlement in NC, GA",current:"142K",projected:"191K"},{lang:"Dari/Pashto",growth:28.7,drivers:"Afghan SIV arrivals in IL, WI",current:"28K",projected:"36K"},{lang:"Burmese",growth:22.1,drivers:"Karen/Chin community growth",current:"63K",projected:"77K"},{lang:"Haitian Creole",growth:19.8,drivers:"TPS migration into SE states",current:"18K",projected:"22K"},{lang:"Swahili",growth:17.4,drivers:"Congolese refugee resettlement",current:"51K",projected:"60K"}],
  alerts:[{alert:"USCIS projecting 12K Afghan arrivals in IL/WI corridor FY2026",severity:"high",action:"Dari/Pashto interpreter recruitment pipeline activated"},{alert:"NC Refugee Office: 40% increase in Arabic-speaking families",severity:"high",action:"Charlotte Arabic capacity expansion underway"},{alert:"Census 2025 supplemental: 18% LEP growth in rural GA counties",severity:"med",action:"Telehealth interpretation pilot for rural facilities"},{alert:"Hmong population shift from WI to NC in ACS data",severity:"med",action:"Cross-state interpreter rebalancing assessment"}]};

const regTracker=[{reg:"HHS Section 1557 Final Rule (2024)",status:"Active",impact:"High",action:"All policies updated; training deployed to 39K",deadline:"Compliant",details:"Expanded definition of language access obligations. Requires taglines in top 15 languages. Video remote interpretation quality standards updated."},{reg:"Executive Order 14091 (Equity)",status:"Monitoring",impact:"Medium",action:"Impact assessment in progress",deadline:"Q2 2026",details:"Federal funding programs may require enhanced language access documentation and reporting."},{reg:"NC HB 442 (Interpreter Standards)",status:"Pending",impact:"High",action:"Credential verification system being built",deadline:"Jul 2026",details:"Requires all medical interpreters in NC to meet state certification standards. Affects 34 interpreters."},{reg:"IL Language Access Act Update",status:"Proposed",impact:"Medium",action:"Advocacy team engaged; comment response drafted",deadline:"TBD",details:"Proposed expansion of language access requirements to outpatient settings. May require additional interpreter FTEs."},{reg:"CMS FY2026 IPPS Language Access",status:"Final Rule",impact:"High",action:"Gap analysis complete; 3 remediation items",deadline:"Oct 2026",details:"New conditions of participation require documented language access plans and interpreter qualification records."},{reg:"Joint Commission PC.02.01.21",status:"Active",impact:"High",action:"Documentation standardized across states",deadline:"Compliant",details:"Interpreter qualification documentation must be maintained for all encounters. Audit-ready status confirmed."}];

const vendors=[{vendor:"Language Line Solutions",type:"OPI/VRI",volume:"1.2M min",fillRate:94.2,avgWait:"45s",cost:"$1.38",satisfaction:91.2,trend:"up",slaStatus:"Meeting",contractEnd:"Dec 2027",details:{totalCost:"$1.66M/mo",peakHours:"7a-11a, 2p-5p",topLangs:"Spanish (68%), Mandarin (12%)",qualityScore:92.4,escalations:12}},{vendor:"AMN Healthcare",type:"OPI/VRI",volume:"320K min",fillRate:84.1,avgWait:"72s",cost:"$1.65",satisfaction:84.6,trend:"down",slaStatus:"Below SLA",contractEnd:"Q2 2026 (transitioning)",details:{totalCost:"$528K/mo",peakHours:"All hours (overflow)",topLangs:"Spanish (72%), Arabic (8%)",qualityScore:81.2,escalations:34}},{vendor:"Internal Team",type:"In-Person/VRI",volume:"890K min",fillRate:96.8,avgWait:"12min",cost:"$0.92",satisfaction:97.4,trend:"up",slaStatus:"Exceeding",contractEnd:"N/A",details:{totalCost:"$818K/mo (salaries)",peakHours:"8a-5p M-F",topLangs:"Spanish (58%), ASL (14%)",qualityScore:98.1,escalations:2}},{vendor:"Certified Languages Intl",type:"Overflow OPI",volume:"180K min",fillRate:91.5,avgWait:"58s",cost:"$1.52",satisfaction:89.1,trend:"stable",slaStatus:"Meeting",contractEnd:"Mar 2027",details:{totalCost:"$274K/mo",peakHours:"Evenings/weekends",topLangs:"Spanish (64%), Hmong (10%)",qualityScore:88.7,escalations:8}},{vendor:"Purple VRS",type:"ASL/VRI",volume:"210K min",fillRate:93.8,avgWait:"90s",cost:"$2.10",satisfaction:92.3,trend:"up",slaStatus:"Meeting",contractEnd:"Jun 2027",details:{totalCost:"$441K/mo",peakHours:"9a-4p M-F",topLangs:"ASL (100%)",qualityScore:94.2,escalations:4}}];

const caseStudies=[{case_name:"Dymally Medical Center (CA, 2023)",outcome:"$4.3M settlement",lesson:"Failed to provide timely interpreter for Spanish-speaking patient in ED, resulting in misdiagnosis and delayed surgery. No language access policy enforced.",category:"Timeliness",preventionAtAH:"Our 45-second OPI connect time and mandatory LEP flagging in Epic would have triggered immediate interpreter dispatch."},{case_name:"UK NHS Trust Coroner Report (2024)",outcome:"Preventable death finding",lesson:"Patient with limited English could not communicate pain symptoms. Family members used as interpreters, missing critical clinical details.",category:"Safety",preventionAtAH:"Advocate Health policy prohibits use of family as interpreters for clinical encounters. All staff trained on interpreter request protocols."},{case_name:"Swedish Hospital (WA, 2022)",outcome:"$2.8M OCR settlement",lesson:"Systemic failure to identify LEP patients at registration. 40% of LEP encounters had no interpreter. OCR found willful noncompliance.",category:"Compliance",preventionAtAH:"Epic LEP flag auto-triggers at registration. Compliance monitoring tracks interpreter utilization vs. LEP encounters at 98.2% match rate."},{case_name:"Toronto General (Canada, 2023)",outcome:"Class action filed",lesson:"Relied exclusively on phone interpretation for complex oncology. Patients reported inability to understand treatment options, leading to uninformed consent claims.",category:"Quality",preventionAtAH:"Our modality routing logic mandates in-person or VRI for high-complexity encounters (oncology, surgical consent, end-of-life)."},{case_name:"Brisbane Health (Australia, 2024)",outcome:"Government inquiry",lesson:"Aboriginal and Torres Strait Islander patients systematically underserved. Inquiry found institutional bias in resource allocation.",category:"Equity",preventionAtAH:"Our census-based demand forecasting and equity radar ensure resources track community demographics, not historical allocation patterns."}];

const stories=[{title:"Maria's Story: A Voice When It Mattered Most",summary:"A Spanish-speaking mother in labor at Carolinas Medical Center received immediate bedside interpretation, enabling her to communicate a critical allergy. The interpreter's presence prevented a potentially fatal medication error.",impact:"Patient Safety",location:"Charlotte, NC",metrics:{encounterTime:"4 min to interpreter arrival",outcome:"Allergy identified, medication changed",patientScore:"10/10 satisfaction"}},{title:"Building Bridges in Clarkston, GA",summary:"Our Burmese interpretation team partnered with local refugee organizations to create a health literacy program. 340 families now navigate the health system independently, reducing ED visits by 28%.",impact:"Community Health",location:"Clarkston, GA",metrics:{familiesServed:"340",edReduction:"28%",costSavings:"$1.2M annually"}},{title:"Ahmed's Journey: From Patient to Interpreter",summary:"A former refugee who relied on our Arabic interpreters during cancer treatment is now a certified medical interpreter on our team, serving the community that once served him.",impact:"Workforce Development",location:"Chicago, IL",metrics:{yearsToCredential:"2.5 years",patientsServed:"1,200+ annually",teamImpact:"Mentors 3 interpreter trainees"}},{title:"Silent No More: ASL Access in Rural Wisconsin",summary:"After identifying a 60% gap in ASL access at rural WI clinics, we deployed VRI stations and trained 120 staff. Deaf patients now report 94% satisfaction, up from 52%.",impact:"Access Equity",location:"Rural Wisconsin",metrics:{satisfactionBefore:"52%",satisfactionAfter:"94%",facilitiesEquipped:"18 rural clinics"}}];

const modalityRules=[{setting:"Emergency Department",complexity:"High",recommended:"In-Person (preferred) or VRI",fallback:"OPI only if wait >10min",reason:"Complex medical terminology, patient distress, time-critical decisions require visual cues and immediate availability",costImpact:"$2.40/min avg",qualityScore:97.2},{setting:"Primary Care Visit",complexity:"Medium",recommended:"VRI (preferred) or In-Person",fallback:"OPI acceptable",reason:"Routine encounters benefit from video for visual communication; phone acceptable for follow-ups and simple visits",costImpact:"$1.52/min avg",qualityScore:93.8},{setting:"Surgical Consent",complexity:"Critical",recommended:"In-Person (required)",fallback:"VRI only if certified interpreter unavailable in-person within 30min",reason:"Informed consent requires full communication fidelity. Regulatory and legal exposure if consent is challenged",costImpact:"$3.10/min avg",qualityScore:98.4},{setting:"Oncology Consultation",complexity:"Critical",recommended:"In-Person (required)",fallback:"VRI with certified oncology interpreter",reason:"Treatment options, prognosis discussion, clinical trial consent require nuanced communication and emotional support",costImpact:"$3.40/min avg",qualityScore:97.8},{setting:"Behavioral Health",complexity:"High",recommended:"In-Person (preferred)",fallback:"VRI; OPI not recommended",reason:"Therapeutic rapport, non-verbal cues, and sensitive disclosures require in-room or video presence",costImpact:"$2.80/min avg",qualityScore:95.1},{setting:"Telehealth Visit",complexity:"Medium",recommended:"OPI or 3-way VRI",fallback:"Bilingual provider if available",reason:"Remote visits naturally integrate phone/video interpretation. Cost-effective for routine follow-ups",costImpact:"$1.28/min avg",qualityScore:91.4},{setting:"Discharge Instructions",complexity:"Medium-High",recommended:"VRI or In-Person",fallback:"OPI with written translation provided",reason:"Patient comprehension critical for medication adherence and follow-up. Written materials supplement verbal",costImpact:"$1.85/min avg",qualityScore:94.2},{setting:"Registration/Scheduling",complexity:"Low",recommended:"OPI (preferred)",fallback:"Bilingual staff or automated system",reason:"Simple, scripted interactions. Phone interpretation most cost-effective. Automated IVR for scheduling",costImpact:"$0.82/min avg",qualityScore:89.6}];

const costModelData={totalBudget:42.8,breakdown:[{cat:"Internal Interpreter Salaries",amt:18.4,pct:43,proj:19.8,note:"164 FTE interpreters across 6 states"},{cat:"Language Line Solutions (OPI/VRI)",amt:9.6,pct:22.4,proj:10.2,note:"Primary vendor, transitioning from AMN"},{cat:"AMN Healthcare (Transitioning)",amt:4.2,pct:9.8,proj:0,note:"Phasing out Q2 2026"},{cat:"Interpreter Technology (VRI/platforms)",amt:3.8,pct:8.9,proj:4.6,note:"Video endpoints, scheduling software, AI tools"},{cat:"Translation Services (Written)",amt:2.4,pct:5.6,proj:2.8,note:"Patient materials, forms, signage in 15+ languages"},{cat:"ASL/VRS Services",amt:2.1,pct:4.9,proj:2.4,note:"Purple VRS and in-person ASL interpreters"},{cat:"Training & Certification",amt:1.4,pct:3.3,proj:1.8,note:"Interpreter development, medical terminology, career ladder"},{cat:"Overflow & Specialty",amt:0.9,pct:2.1,proj:0.6,note:"CLI overflow, rare language sourcing"}],
  scenarios:[{name:"Baseline (organic)",growth:5.4,total:45.1},{name:"SE Market Expansion",growth:12.8,total:48.3},{name:"AI-Augmented Model",growth:8.2,total:46.3,savings:3.8}]};

const feedbackData=[{source:"Patient Satisfaction (Post-Encounter)",frequency:"Every encounter",lastRun:"Rolling",rate:"42.8%",findings:["Spanish interpretation: 94.2% satisfaction","Wait time >10min drops satisfaction 18pts","VRI preferred over OPI by patients (72%)","ASL patients: 94% satisfaction (up from 52%)"],actions:["VRI expansion to 12 additional facilities","Wait time reduction initiative launched","ASL VRI stations added to 18 rural clinics"]},{source:"Interpreter Feedback Portal",frequency:"Continuous",lastRun:"Rolling",rate:"68.4%",findings:["Technology reliability concern (VRI connectivity)","Request for more oncology-specific training","Career pathway visibility has improved","Scheduling flexibility requested for PT staff"],actions:["VRI infrastructure upgrade funded ($1.2M)","Oncology medical terminology course launched","Career ladder communication campaign","Flexible scheduling pilot in IL market"]},{source:"Clinician Experience Survey",frequency:"Quarterly",lastRun:"Q1 2026",rate:"34.2%",findings:["89% find interpreter easy to request","42% want faster in-person response","Prefer VRI over phone for complex visits","Request interpreter consistency for ongoing care"],actions:["Dedicated interpreter assignment pilot (oncology)","In-person response time goal: <15min","VRI-first protocol for specialty visits"]},{source:"Community Advisory Input",frequency:"Bi-Monthly",lastRun:"Feb 2026",rate:"N/A (186 attendees)",findings:["Hmong community: want same interpreter each visit","Arabic families: desire female interpreters for OB","Burmese community: health literacy gap identified","Deaf community: praise for VRI expansion"],actions:["Interpreter continuity matching system designed","Gender-preference flag added to Epic workflow","Burmese health literacy program launched","Deaf community advisory panel established"]}];

const govData=[{body:"Language Services Steering Committee",chair:"Emmanuel (AVP)",frequency:"Bi-Weekly",members:14,lastMeeting:"Mar 5, 2026",decisions:["Approved Language Line full migration timeline","Endorsed interpreter career ladder v2","Set Q2 fill rate targets by region"]},{body:"Vendor Performance Review Board",chair:"Dir. Vendor Mgmt",frequency:"Monthly",members:8,lastMeeting:"Mar 3, 2026",decisions:["Issued AMN performance improvement notice","Approved CLI overflow expansion","Set SLA thresholds for FY27 contracts"]},{body:"Regulatory Compliance Working Group",chair:"Compliance Officer",frequency:"Monthly",members:10,lastMeeting:"Feb 28, 2026",decisions:["Approved 1557 policy updates","NC HB 442 response plan finalized","CMS IPPS remediation items assigned"]},{body:"Interpreter Advisory Council",chair:"Lead Interpreter (elected)",frequency:"Monthly",members:12,lastMeeting:"Mar 1, 2026",decisions:["Endorsed career ladder compensation bands","Requested scheduling flexibility pilot","Proposed interpreter recognition program"]}];

const predictModels=[{model:"Interpreter Demand Forecaster",status:"Active",accuracy:"91.8%",desc:"Combines Epic scheduling, Census ACS, USCIS data, and historical patterns to predict interpreter need by language, facility, and hour 7-30 days ahead",predictions:[{p:"Mandarin demand at Carolinas MC will spike 40% weeks of Mar 17-28 (Lunar New Year follow-ups)",confidence:"92%",action:"Pre-schedule 3 additional Mandarin interpreters"},{p:"Dari/Pashto demand in IL will exceed capacity by Q3 if no new hires",confidence:"87%",action:"Activate recruitment pipeline (4 FTEs needed)"},{p:"ASL VRI utilization in rural WI will plateau; recommend in-person for complex visits",confidence:"84%",action:"Hire 2 ASL interpreters for WI rural circuit"}]},{model:"Vendor SLA Predictor",status:"Active",accuracy:"88.4%",desc:"Predicts vendor performance degradation 2-4 weeks ahead based on staffing patterns, volume trends, and seasonal factors",predictions:[{p:"Language Line fill rate will drop to 91% during spring break (Mar 15-22)",confidence:"86%",action:"Pre-activate CLI overflow for peak hours"},{p:"AMN quality scores will continue declining through transition",confidence:"94%",action:"Accelerate migration timeline by 2 weeks"},{p:"Purple VRS capacity sufficient through Q3; Q4 may need expansion",confidence:"81%",action:"Begin Q4 capacity planning with Purple"}]},{model:"Cost Optimization Engine",status:"Building",accuracy:"82.1%",desc:"Models cost impact of modality mix changes, vendor shifts, and internal capacity expansion to find optimal resource allocation",predictions:[{p:"Shifting 15% of OPI encounters to VRI would save $1.2M annually with no quality drop",confidence:"89%",action:"Launch OPI-to-VRI migration for primary care"},{p:"Adding 8 internal interpreters in SE would reduce vendor spend by $2.1M",confidence:"85%",action:"Business case submitted for 8 FTEs"},{p:"AI-assisted pre-screening could reduce interpreter time per encounter by 12%",confidence:"72%",action:"Pilot AI pre-screening in IL market"}]}];

const dataAgg={sources:[{name:"Epic EHR (LEP Flags)",records:"12.4M patients",fields:["LEP flag","Preferred language","Interpreter requests","Encounter type"],refresh:"Real-time",quality:97.8},{name:"Interpreter Management System",records:"2.85M encounters",fields:["Language","Modality","Duration","Interpreter ID","Satisfaction"],refresh:"5 min",quality:96.4},{name:"Census ACS / USCIS",records:"6-state demographics",fields:["Language spoken at home","English proficiency","Migration","Refugee data"],refresh:"Annual + supplements",quality:94.2},{name:"Vendor APIs (LLS/CLI/Purple)",records:"1.71M minutes",fields:["Fill rate","Wait time","Cost","Quality score","SLA status"],refresh:"15 min",quality:95.8},{name:"Patient Satisfaction System",records:"1.2M surveys",fields:["Interpreter satisfaction","Communication score","Wait time rating"],refresh:"Continuous",quality:88.4},{name:"Financial Systems",records:"$42.8M tracked",fields:["Cost per minute","Vendor invoices","Internal salary cost","Budget vs actual"],refresh:"Daily",quality:97.1}],qualityScore:95.0};

const projects=[{name:"SE/MW Language Services Consolidation",progress:58,status:"In Progress",owner:"Emmanuel (AVP)",due:"Q3 2026",priority:"Critical"},{name:"Language Line Solutions Full Migration",progress:72,status:"In Progress",owner:"Vendor Mgmt",due:"Q2 2026",priority:"Critical"},{name:"Interpreter Career Ladder v2",progress:85,status:"Launched",owner:"HR + LS",due:"Complete",priority:"High"},{name:"KIP-Coordinator Pro Platform",progress:40,status:"Development",owner:"Emmanuel / Tech",due:"Q3 2026",priority:"High"},{name:"Predictive Demand Engine",progress:55,status:"Building",owner:"AI Ops + LS",due:"Q4 2026",priority:"High"},{name:"VRI Infrastructure Upgrade",progress:30,status:"Funded",owner:"IT + LS",due:"Q3 2026",priority:"High"},{name:"AI Interpreter Copilot Pilot",progress:15,status:"Planning",owner:"AI Ops",due:"Q4 2026",priority:"Medium"},{name:"Burmese Health Literacy Program",progress:45,status:"Active",owner:"Community Relations",due:"Q3 2026",priority:"Medium"}];

/* ═══ AGENT ═══ */
type Msg={role:"user"|"agent"|"sys";content:string;ts:string;actions?:string[]};
function AgentPanel(){
  const[msgs,setMsgs]=useState<Msg[]>([{role:"sys",content:"Language Services Agent online.\nConnected: Epic, Interpreter CMS, Census/USCIS, Vendor APIs, Patient Satisfaction, Financial.\n6 data sources. Modality routing, demand forecasting, and vendor intelligence active.",ts:"09:00"}]);
  const[inp,setInp]=useState("");const[thinking,setThinking]=useState(false);const ref=useRef<HTMLDivElement>(null);
  const respond=(q:string)=>{setThinking(true);const ql=q.toLowerCase();let r={content:"Searching 6 connected systems...\n\nAsk about demand forecasts, vendor SLAs, modality routing, census trends, cost optimization, or regulatory updates.",actions:["Full domain scan","Executive brief"]};
    if(ql.includes("demand")||ql.includes("forecast")||ql.includes("predict"))r={content:"\u{1F4CA} Demand Forecast\n\nMandarin: +40% at Carolinas MC (Mar 17-28)\nDari/Pashto: will exceed IL capacity by Q3\nASL rural WI: plateauing, shift to in-person recommended\n\nTotal LEP growth: 1.82M \u2192 2.34M by 2030\nFastest: Arabic (+34.2%), Dari (+28.7%)\n\n\u26A0\uFE0F 4 Dari/Pashto FTEs needed by Q3.",actions:["View full forecast","Activate recruitment","Budget impact"]};
    else if(ql.includes("vendor")||ql.includes("sla")||ql.includes("language line")||ql.includes("amn"))r={content:"\u{1F4E6} Vendor Status\n\nLanguage Line: 94.2% fill \u2714\uFE0F\nAMN: 84.1% \u26A0\uFE0F BELOW SLA (transitioning)\nInternal: 96.8% \u2B50 highest quality\nCLI: 91.5% (overflow)\nPurple VRS: 93.8% (ASL)\n\nAMN migration 72% complete. Target: Q2.\nPredicted: LLS fill may drop to 91% spring break week.\n\n\u{1F6A8} Pre-activate CLI overflow Mar 15-22.",actions:["Escalate AMN","Accelerate migration","Spring break plan"]};
    else if(ql.includes("modality")||ql.includes("routing")||ql.includes("vri")||ql.includes("opi"))r={content:"\u{1F500} Modality Routing Analysis\n\nCurrent mix: In-Person 42%, VRI 31%, OPI 27%\nOptimal mix: In-Person 38%, VRI 40%, OPI 22%\n\nShifting 15% OPI to VRI saves $1.2M/yr with no quality drop.\n\nCritical settings (surgery, oncology): In-person required.\nTelehealth: OPI/3-way VRI most efficient.\nRegistration: OPI or automated IVR.\n\nModality routing engine active for all new encounters.",actions:["View routing rules","Run cost simulation","Quality impact report"]};
    else if(ql.includes("cost")||ql.includes("budget"))r={content:"\u{1F4B5} Cost Model\n\nTotal: $42.8M\nInternal (cheapest): $0.92/min, 43% of budget\nLLS: $1.38/min, 22.4%\nAMN: $1.65/min \u2192 $0 after Q2 transition\n\nScenarios:\n\u2022 Baseline: $45.1M (+5.4%)\n\u2022 SE Expansion: $48.3M (+12.8%)\n\u2022 AI-Augmented: $46.3M (+8.2%, saves $3.8M)\n\nBiggest savings lever: +8 internal hires in SE = -$2.1M vendor spend.",actions:["Run scenario model","Hire vs vendor analysis","CFO brief"]};
    setTimeout(()=>{setMsgs(p=>[...p,{role:"agent",content:r.content,ts:new Date().toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"}),actions:r.actions}]);setThinking(false);},1600);};
  const send=()=>{if(!inp.trim())return;const ts=new Date().toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"});setMsgs(p=>[...p,{role:"user",content:inp,ts}]);respond(inp);setInp("");};
  useEffect(()=>{ref.current?.scrollTo({top:ref.current.scrollHeight,behavior:"smooth"});},[msgs]);
  return(<div className="flex flex-col h-full"><div className="flex items-center gap-2 px-4 py-3 border-b border-[#1e2d3d]"><div className="w-2 h-2 rounded-full bg-emerald-400 animate-pulse"/><span className="text-xs font-semibold text-[#8ab4d8] tracking-wider uppercase">Language Services Agent</span><Badge variant="outline" className="ml-auto text-[10px] border-emerald-500/30 text-emerald-400">6 Sources</Badge></div>
    <ScrollArea className="flex-1 p-4" ref={ref}><div className="space-y-3">{msgs.map((m,i)=>(<div key={i} className={`flex ${m.role==="user"?"justify-end":"justify-start"}`}><div className={`max-w-[90%] rounded-lg px-3 py-2 text-sm ${m.role==="user"?"bg-[#1a3a5c] text-[#c8dff0] border border-[#2a5a8c]":m.role==="sys"?"bg-[#0a1520] text-[#4a7a9a] border border-[#162535] font-mono text-xs":"bg-[#111f2e] text-[#a8c8e0] border border-[#1e2d3d]"}`}><div className="whitespace-pre-wrap">{m.content}</div>{m.actions&&<div className="flex flex-wrap gap-1.5 mt-2 pt-2 border-t border-[#1e2d3d]">{m.actions.map((a,j)=><button key={j} className="text-[10px] px-2 py-1 rounded bg-[#1a3a5c] text-[#8ab4d8] border border-[#2a5a8c] hover:bg-[#2a5a8c] transition-colors">{a}</button>)}</div>}</div></div>))}{thinking&&<div className="flex justify-start"><div className="bg-[#111f2e] border border-[#1e2d3d] rounded-lg px-4 py-3"><div className="flex gap-1.5">{[0,150,300].map(d=><div key={d} className="w-2 h-2 rounded-full bg-[#3a7abd] animate-bounce" style={{animationDelay:`${d}ms`}}/>)}</div></div></div>}</div></ScrollArea>
    <div className="p-3 border-t border-[#1e2d3d]"><div className="flex flex-wrap gap-1.5 mb-2">{["Demand forecast","Vendor SLA status","Modality routing analysis","Cost model scenarios"].map((q,i)=><button key={i} onClick={()=>{const ts=new Date().toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"});setMsgs(p=>[...p,{role:"user",content:q,ts}]);respond(q);}} className="text-[10px] px-2 py-1 rounded-full border border-[#1e2d3d] text-[#6b8aad] hover:border-[#3a7abd] hover:text-[#8ab4d8] transition-colors">{q}</button>)}</div><div className="flex gap-2"><Input value={inp} onChange={e=>setInp(e.target.value)} onKeyDown={e=>e.key==="Enter"&&send()} placeholder="Ask about language services..." className="bg-[#0a1520] border-[#1e2d3d] text-[#c8dff0] placeholder:text-[#3a5a7a] text-sm focus-visible:ring-[#2a5a8c]"/><Button onClick={send} size="sm" className="bg-[#1a3a5c] hover:bg-[#2a5a8c] border border-[#2a5a8c]"><I.Send/></Button></div></div></div>);
}

/* ═══ VIEWS ═══ */
type Section="dash"|"ops"|"census"|"reg"|"vendors"|"modality"|"cost"|"stories"|"cases"|"feedback"|"gov"|"predict"|"data"|"projects";

function DashView(){return(<div className="space-y-6 animate-in fade-in duration-300"><div><h2 className="text-lg font-semibold text-[#e8f0f8] flex items-center gap-2"><I.Globe size={20}/> Enterprise Language Services</h2><p className="text-xs text-[#4a6a8a] mt-1">6 states, 164 interpreters, 247 languages, ASL, $42.8M budget</p></div>
  <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">
    <DrillCard title="Total Encounters" value="2.85M" change={12.3} spark={[180,195,210,225,218,240,252,261,248,270,282,285]} color="#3a7abd" icon={<I.Activity/>}><div className="space-y-2 mt-4">{regions.map(r=><div key={r.r} className="flex items-center gap-3"><Dot s={r.s}/><span className="w-24 text-xs text-[#a8c8e0]">{r.r}</span><span className="text-xs font-mono text-[#6b8aad]">{r.vol}</span><span className="text-[10px] text-emerald-400">+{r.growth}%</span></div>)}</div></DrillCard>
    <DrillCard title="Internal Fill Rate" value="68.4" unit="%" change={4.2} spark={[58,60,62,61,64,63,66,65,67,66,68,68]} color="#10b981" icon={<I.TrendUp/>}><div className="space-y-2 mt-4">{regions.map(r=><div key={r.r} className="flex items-center gap-3"><span className="w-24 text-xs text-[#a8c8e0]">{r.r}</span><div className="flex-1"><Progress value={r.fill} className="h-1.5 bg-[#162535]"/></div><span className="text-xs font-mono text-[#6b8aad]">{r.fill}%</span><span className="text-[10px] text-[#4a6a8a]">{r.interpreters} interp.</span></div>)}</div></DrillCard>
    <DrillCard title="Cost / Minute" value="$1.42" change={-8.1} spark={[1.8,1.75,1.7,1.65,1.6,1.55,1.52,1.5,1.48,1.45,1.43,1.42]} color="#f59e0b" icon={<I.Dollar/>}><div className="space-y-2 mt-4">{regions.map(r=><div key={r.r} className="flex items-center gap-3"><span className="w-24 text-xs text-[#a8c8e0]">{r.r}</span><span className="text-xs font-mono text-[#6b8aad]">${r.costPerMin}</span></div>)}<Separator className="bg-[#1e2d3d] my-2"/>{vendors.map(v=><div key={v.vendor} className="flex items-center gap-3"><span className="flex-1 text-xs text-[#a8c8e0]">{v.vendor}</span><span className="text-xs font-mono text-[#6b8aad]">{v.cost}</span></div>)}</div></DrillCard>
    <DrillCard title="LEP Population" value="1.82M" change={6.7} spark={[1.4,1.45,1.5,1.52,1.55,1.6,1.62,1.65,1.7,1.72,1.76,1.82]} color="#8b5cf6" icon={<I.Map/>}><div className="space-y-2 mt-4">{regions.map(r=><div key={r.r} className="flex items-center gap-3"><span className="w-24 text-xs text-[#a8c8e0]">{r.r}</span><span className="text-xs font-mono text-[#6b8aad]">{r.lep}</span><span className="text-[10px] text-amber-400">+{r.growth}%</span></div>)}<Separator className="bg-[#1e2d3d] my-2"/><p className="text-xs text-[#4a6a8a]">Projected 2030: {censusData.projected5yr} (+{censusData.growthRate}%)</p></div></DrillCard>
  </div>
  <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
    <Card className="bg-[#0f1923] border-[#1e2d3d]"><CardHeader className="pb-2"><CardTitle className="text-sm text-[#8ab4d8]">Top Languages</CardTitle></CardHeader><CardContent>{topLangs.slice(0,6).map(l=><div key={l.lang} className="flex items-center gap-2 py-1.5"><div className="w-16 text-xs text-[#a8c8e0]">{l.lang}</div><div className="flex-1 h-1.5 bg-[#162535] rounded-full overflow-hidden"><div className="h-full rounded-full" style={{width:`${l.pct}%`,backgroundColor:l.c}}/></div><span className="text-[10px] font-mono text-[#4a6a8a]">{l.pct}%</span></div>)}</CardContent></Card>
    <Card className="bg-[#0f1923] border-[#1e2d3d]"><CardHeader className="pb-2"><CardTitle className="text-sm text-[#8ab4d8]">Vendor Health</CardTitle></CardHeader><CardContent>{vendors.map(v=><div key={v.vendor} className="flex items-center gap-2 py-1.5"><Dot s={v.slaStatus==="Below SLA"?"crit":v.slaStatus==="Exceeding"?"on":"on"}/><span className="flex-1 text-xs text-[#a8c8e0]">{v.vendor.length>20?v.vendor.slice(0,20)+"...":v.vendor}</span><span className={`text-[10px] font-mono ${v.fillRate>=90?"text-emerald-400":"text-red-400"}`}>{v.fillRate}%</span></div>)}</CardContent></Card>
    <Card className="bg-[#0f1923] border-[#1e2d3d]"><CardHeader className="pb-2"><CardTitle className="text-sm text-[#8ab4d8]">Critical Projects</CardTitle></CardHeader><CardContent>{projects.filter(p=>p.priority==="Critical").map(p=><div key={p.name} className="py-1.5 border-b border-[#162535] last:border-0"><div className="flex justify-between text-xs mb-1"><span className="text-[#a8c8e0]">{p.name.length>30?p.name.slice(0,30)+"...":p.name}</span><span className="font-mono text-[#6b8aad]">{p.progress}%</span></div><Progress value={p.progress} className="h-1 bg-[#162535]"/></div>)}</CardContent></Card>
  </div></div>);}

function OpsView(){return(<div className="space-y-6 animate-in fade-in duration-300"><div><h2 className="text-lg font-semibold text-[#e8f0f8]">Operations Deep Dive</h2><p className="text-xs text-[#4a6a8a] mt-1">Drillable language and regional performance data</p></div>
  <Card className="bg-[#0f1923] border-[#1e2d3d]"><CardHeader className="pb-2"><CardTitle className="text-sm text-[#8ab4d8]">Languages (with modality mix)</CardTitle></CardHeader><CardContent className="space-y-1">{topLangs.map(l=><DrillRow key={l.lang} label={`${l.lang} - ${l.enc} encounters (${l.pct}%)`}><div className="grid grid-cols-4 gap-3"><div><span className="text-[#4a6a8a]">In-Person</span><div className="text-[#a8c8e0] font-mono">{l.inPerson}%</div></div><div><span className="text-[#4a6a8a]">VRI</span><div className="text-[#a8c8e0] font-mono">{l.vri}%</div></div><div><span className="text-[#4a6a8a]">OPI</span><div className="text-[#a8c8e0] font-mono">{l.opi}%</div></div><div><span className="text-[#4a6a8a]">Cost/Min</span><div className="text-amber-400 font-mono">${l.cost}</div></div></div></DrillRow>)}</CardContent></Card>
  <Card className="bg-[#0f1923] border-[#1e2d3d]"><CardHeader className="pb-2"><CardTitle className="text-sm text-[#8ab4d8]">Regional Deep Dive</CardTitle></CardHeader><CardContent className="space-y-1">{regions.map(r=><DrillRow key={r.r} label={`${r.r} - ${r.fill}% fill rate, ${r.vol} encounters`}><div className="grid grid-cols-2 md:grid-cols-4 gap-3"><div><span className="text-[#4a6a8a]">LEP Pop</span><div className="text-[#a8c8e0] font-mono">{r.lep}</div></div><div><span className="text-[#4a6a8a]">Growth</span><div className="text-amber-400 font-mono">+{r.growth}%</div></div><div><span className="text-[#4a6a8a]">Interpreters</span><div className="text-[#a8c8e0] font-mono">{r.interpreters}</div></div><div><span className="text-[#4a6a8a]">Satisfaction</span><div className="text-emerald-400 font-mono">{r.satisfaction}%</div></div></div><div className="mt-2"><span className="text-[#4a6a8a]">Cost/min: </span><span className="text-amber-400 font-mono">${r.costPerMin}</span></div></DrillRow>)}</CardContent></Card></div>);}

function CensusView(){return(<div className="space-y-6 animate-in fade-in duration-300"><div><h2 className="text-lg font-semibold text-[#e8f0f8] flex items-center gap-2"><I.Map size={20}/> Census, Migration & Community</h2></div>
  <div className="grid grid-cols-3 gap-3">{[{l:"Current LEP",v:censusData.totalLEP,c:"text-[#e8f0f8]"},{l:"Projected 2030",v:censusData.projected5yr,c:"text-amber-400"},{l:"Growth Rate",v:`+${censusData.growthRate}%`,c:"text-emerald-400"}].map(x=><div key={x.l} className="bg-[#0f1923] border border-[#1e2d3d] rounded-lg p-4 text-center"><div className={`text-2xl font-semibold ${x.c}`}>{x.v}</div><div className="text-[10px] text-[#4a6a8a]">{x.l}</div></div>)}</div>
  <Card className="bg-[#0f1923] border-[#1e2d3d]"><CardHeader className="pb-2"><CardTitle className="text-sm text-[#8ab4d8]">Fastest Growing Languages</CardTitle></CardHeader><CardContent className="space-y-1">{censusData.growthLangs.map(l=><DrillRow key={l.lang} label={`${l.lang} +${l.growth}% (${l.current} \u2192 ${l.projected})`}><p className="text-[#4a6a8a]">Drivers: {l.drivers}</p><p className="text-[#4a6a8a] mt-1">Current capacity assessment and recruitment pipeline status available through the agent.</p></DrillRow>)}</CardContent></Card>
  <Card className="bg-[#0f1923] border-[#1e2d3d]"><CardHeader className="pb-2"><CardTitle className="text-sm text-[#8ab4d8] flex items-center gap-2"><I.Alert/> Migration & Resettlement Alerts</CardTitle></CardHeader><CardContent className="space-y-3">{censusData.alerts.map((a,i)=><div key={i} className="bg-[#0a1520] border border-[#162535] rounded-lg p-3"><div className="flex items-start gap-2"><Badge variant="outline" className={`text-[10px] shrink-0 mt-0.5 ${a.severity==="high"?"border-red-500/30 text-red-400":"border-amber-500/30 text-amber-400"}`}>{a.severity}</Badge><div><div className="text-xs text-[#a8c8e0]">{a.alert}</div><div className="text-[11px] text-emerald-400/80 mt-1">Action: {a.action}</div></div></div></div>)}</CardContent></Card></div>);}

function RegView(){return(<div className="space-y-6 animate-in fade-in duration-300"><div><h2 className="text-lg font-semibold text-[#e8f0f8] flex items-center gap-2"><I.Shield size={20}/> Laws, Regulation & Compliance</h2></div>
  <Card className="bg-[#0f1923] border-[#1e2d3d]"><CardContent className="p-0">{regTracker.map(r=><DrillRow key={r.reg} label={`${r.reg}`}><div className="flex gap-2 mb-2"><Badge variant="outline" className={`text-[10px] ${r.impact==="High"?"border-red-500/30 text-red-400":"border-amber-500/30 text-amber-400"}`}>{r.impact} Impact</Badge><Badge variant="outline" className="text-[10px] border-[#2a4a6b] text-[#6b8aad]">{r.status}</Badge></div><p className="text-[#a8c8e0]">{r.details}</p><p className="text-emerald-400/80 mt-1">Action: {r.action}</p><p className="text-[#3a5a7a] mt-1">Deadline: {r.deadline}</p></DrillRow>)}</CardContent></Card></div>);}

function VendorView(){return(<div className="space-y-6 animate-in fade-in duration-300"><div><h2 className="text-lg font-semibold text-[#e8f0f8]">Vendor Performance Dashboard</h2></div>
  {vendors.map(v=><Card key={v.vendor} className="bg-[#0f1923] border-[#1e2d3d]"><CardContent className="p-4"><div className="flex items-center justify-between mb-3"><div className="flex items-center gap-2"><Dot s={v.slaStatus==="Below SLA"?"crit":"on"}/><h3 className="text-sm font-medium text-[#e8f0f8]">{v.vendor}</h3></div><div className="flex gap-2"><Badge variant="outline" className={`text-[10px] ${v.slaStatus==="Below SLA"?"border-red-500/30 text-red-400":"border-emerald-500/30 text-emerald-400"}`}>{v.slaStatus}</Badge><Badge variant="outline" className="text-[10px] border-[#2a4a6b] text-[#6b8aad]">{v.type}</Badge></div></div>
    <div className="grid grid-cols-3 md:grid-cols-6 gap-3 mb-3">{[{l:"Volume",v:v.volume},{l:"Fill Rate",v:`${v.fillRate}%`},{l:"Avg Wait",v:v.avgWait},{l:"Cost/Min",v:v.cost},{l:"Satisfaction",v:`${v.satisfaction}%`},{l:"Contract End",v:v.contractEnd}].map(x=><div key={x.l} className="text-center"><div className="text-[10px] text-[#4a6a8a]">{x.l}</div><div className="text-xs font-mono text-[#a8c8e0]">{x.v}</div></div>)}</div>
    <DrillRow label="Detailed Performance Metrics"><div className="grid grid-cols-2 md:grid-cols-3 gap-3">{Object.entries(v.details).map(([k,val])=><div key={k}><span className="text-[#4a6a8a] capitalize">{k.replace(/([A-Z])/g," $1")}: </span><span className="text-[#a8c8e0]">{val}</span></div>)}</div></DrillRow></CardContent></Card>)}</div>);}

function ModalityView(){const[sim,setSim]=useState({inPerson:42,vri:31,opi:27});const totalCost=(sim.inPerson*2.4+sim.vri*1.52+sim.opi*1.28)/100;
  return(<div className="space-y-6 animate-in fade-in duration-300"><div><h2 className="text-lg font-semibold text-[#e8f0f8] flex items-center gap-2"><I.Route size={20}/> Modality Routing Logic</h2><p className="text-xs text-[#4a6a8a] mt-1">Rules engine for In-Person, VRI, and OPI assignment by clinical setting</p></div>
  <Card className="bg-[#0f1923] border-[#1e2d3d]"><CardHeader className="pb-2"><CardTitle className="text-sm text-[#8ab4d8]">Modality Mix Simulator</CardTitle></CardHeader><CardContent><div className="grid grid-cols-3 gap-4 mb-4">{[{l:"In-Person",v:sim.inPerson,c:"#3a7abd",set:(n:number)=>setSim({...sim,inPerson:n,opi:100-n-sim.vri})},{l:"VRI",v:sim.vri,c:"#10b981",set:(n:number)=>setSim({...sim,vri:n,opi:100-sim.inPerson-n})},{l:"OPI",v:sim.opi,c:"#f59e0b",set:()=>{}}].map(x=><div key={x.l}><div className="flex justify-between text-xs mb-1"><span className="text-[#a8c8e0]">{x.l}</span><span className="font-mono text-[#6b8aad]">{x.v}%</span></div>{x.l!=="OPI"?<Slider value={[x.v]} onValueChange={([n])=>x.set(Math.max(0,Math.min(n,100-sim[x.l==="In-Person"?"vri":"inPerson"])))} max={80} step={1} className="mt-2"/>:<Progress value={x.v} className="h-2 bg-[#162535] mt-3"/>}</div>)}</div>
    <div className="bg-[#0a1520] border border-[#162535] rounded-lg p-3 flex items-center justify-between"><span className="text-xs text-[#a8c8e0]">Blended Cost/Minute:</span><span className="text-lg font-semibold text-amber-400">${totalCost.toFixed(2)}</span></div></CardContent></Card>
  <Card className="bg-[#0f1923] border-[#1e2d3d]"><CardHeader className="pb-2"><CardTitle className="text-sm text-[#8ab4d8]">Routing Rules by Clinical Setting</CardTitle></CardHeader><CardContent className="space-y-1">{modalityRules.map(r=><DrillRow key={r.setting} label={`${r.setting} (${r.complexity})`}><div className="space-y-2"><div><span className="text-[#4a6a8a]">Recommended: </span><span className="text-emerald-400">{r.recommended}</span></div><div><span className="text-[#4a6a8a]">Fallback: </span><span className="text-amber-400">{r.fallback}</span></div><div><span className="text-[#4a6a8a]">Rationale: </span><span className="text-[#a8c8e0]">{r.reason}</span></div><div className="flex gap-4 mt-1"><span className="text-[#4a6a8a]">Cost: <span className="text-amber-400 font-mono">{r.costImpact}</span></span><span className="text-[#4a6a8a]">Quality: <span className="text-emerald-400 font-mono">{r.qualityScore}%</span></span></div></div></DrillRow>)}</CardContent></Card></div>);}

function CostView(){const[sc,setSc]=useState(0);return(<div className="space-y-6 animate-in fade-in duration-300"><div><h2 className="text-lg font-semibold text-[#e8f0f8] flex items-center gap-2"><I.Dollar size={20}/> Cost Modeling</h2></div>
  <div className="grid grid-cols-3 gap-3">{costModelData.scenarios.map((s,i)=><button key={s.name} onClick={()=>setSc(i)} className={`rounded-lg p-4 text-center transition-all ${sc===i?"bg-[#1a2a3c] border border-[#2a4a6b]":"bg-[#0f1923] border border-[#1e2d3d] hover:border-[#2a4a6b]"}`}><div className="text-xs text-[#6b8aad] mb-1">{s.name}</div><div className="text-xl font-semibold text-[#e8f0f8]">${s.total}M</div><div className="text-[10px] text-emerald-400">+{s.growth}%</div>{"savings" in s&&<div className="text-[10px] text-amber-400 mt-1">Saves ${s.savings}M</div>}</button>)}</div>
  <Card className="bg-[#0f1923] border-[#1e2d3d]"><CardHeader className="pb-2"><CardTitle className="text-sm text-[#8ab4d8]">Budget Breakdown (${costModelData.totalBudget}M)</CardTitle></CardHeader><CardContent className="space-y-1">{costModelData.breakdown.map(b=><DrillRow key={b.cat} label={`${b.cat} - $${b.amt}M (${b.pct}%)`}><div className="grid grid-cols-2 gap-4"><div><span className="text-[#4a6a8a]">Current: </span><span className="font-mono text-[#a8c8e0]">${b.amt}M</span></div><div><span className="text-[#4a6a8a]">Projected: </span><span className="font-mono text-amber-400">${b.proj}M</span></div></div><p className="text-[#4a6a8a] mt-1">{b.note}</p><Progress value={b.pct} className="h-2 bg-[#162535] mt-2"/></DrillRow>)}</CardContent></Card></div>);}

function StoriesView(){return(<div className="space-y-6 animate-in fade-in duration-300"><div><h2 className="text-lg font-semibold text-[#e8f0f8] flex items-center gap-2"><I.Heart size={20}/> Connect to Purpose</h2></div>
  {stories.map(s=><Card key={s.title} className="bg-[#0f1923] border-[#1e2d3d]"><CardContent className="p-4"><div className="flex items-start justify-between mb-2"><h3 className="text-sm font-medium text-[#e8f0f8]">{s.title}</h3><Badge variant="outline" className="text-[10px] border-[#2a4a6b] text-[#6b8aad] shrink-0 ml-2">{s.impact}</Badge></div><p className="text-xs text-[#a8c8e0] leading-relaxed mb-3">{s.summary}</p><div className="text-[10px] text-[#4a6a8a] mb-3">{s.location}</div><div className="grid grid-cols-3 gap-3">{Object.entries(s.metrics).map(([k,v])=><div key={k} className="bg-[#0a1520] border border-[#162535] rounded p-2 text-center"><div className="text-[10px] text-[#4a6a8a] capitalize">{k.replace(/([A-Z])/g," $1")}</div><div className="text-xs font-mono text-[#a8c8e0]">{v}</div></div>)}</div></CardContent></Card>)}</div>);}

function CasesView(){return(<div className="space-y-6 animate-in fade-in duration-300"><div><h2 className="text-lg font-semibold text-[#e8f0f8] flex items-center gap-2"><I.Alert size={20}/> Global Case Studies: When Language Access Fails</h2></div><div className="bg-[#1a1520] border border-red-500/20 rounded-lg p-3 mb-2"><p className="text-xs text-red-300/80">These cases illustrate what is at stake when language services fall short. Each includes how Advocate Health's systems would prevent the same outcome.</p></div>
  {caseStudies.map(c=><Card key={c.case_name} className="bg-[#0f1923] border-[#1e2d3d]"><CardContent className="p-4"><div className="flex items-start justify-between mb-2"><h3 className="text-sm font-medium text-[#e8f0f8]">{c.case_name}</h3><Badge variant="outline" className="text-[10px] border-red-500/30 text-red-400 shrink-0 ml-2">{c.outcome}</Badge></div><p className="text-xs text-[#a8c8e0] leading-relaxed mb-2">{c.lesson}</p><div className="bg-[#0a1520] border border-emerald-500/20 rounded-lg p-3 mt-2"><div className="text-[10px] uppercase tracking-wider text-emerald-400/60 mb-1">Our Prevention</div><p className="text-[11px] text-emerald-400/80">{c.preventionAtAH}</p></div><Badge variant="outline" className="text-[10px] border-[#2a4a6b] text-[#6b8aad] mt-2">{c.category}</Badge></CardContent></Card>)}</div>);}

function FeedbackView(){return(<div className="space-y-6 animate-in fade-in duration-300"><div><h2 className="text-lg font-semibold text-[#e8f0f8] flex items-center gap-2"><I.Msg size={20}/> Feedback Loops</h2></div>
  {feedbackData.map(f=><Card key={f.source} className="bg-[#0f1923] border-[#1e2d3d]"><CardContent className="p-4"><div className="flex items-center justify-between mb-3"><h3 className="text-sm font-medium text-[#e8f0f8]">{f.source}</h3><div className="flex gap-2"><Badge variant="outline" className="text-[10px] border-[#2a4a6b] text-[#6b8aad]">{f.frequency}</Badge><Badge variant="outline" className="text-[10px] border-[#2a4a6b] text-[#6b8aad]">{f.rate}</Badge></div></div><div className="grid grid-cols-1 md:grid-cols-2 gap-4"><div><div className="text-[10px] uppercase tracking-wider text-[#3a5a7a] mb-2">Key Findings</div>{f.findings.map((k,i)=><div key={i} className="flex items-start gap-2 py-1 text-[11px] text-[#a8c8e0]"><I.ChevR className="shrink-0 mt-0.5 text-[#4a6a8a]"/>{k}</div>)}</div><div><div className="text-[10px] uppercase tracking-wider text-[#3a5a7a] mb-2">Actions Taken</div>{f.actions.map((a,i)=><div key={i} className="flex items-start gap-2 py-1 text-[11px] text-emerald-400/80"><I.Check className="shrink-0 mt-0.5"/>{a}</div>)}</div></div></CardContent></Card>)}</div>);}

function GovView(){return(<div className="space-y-6 animate-in fade-in duration-300"><div><h2 className="text-lg font-semibold text-[#e8f0f8] flex items-center gap-2"><I.Shield size={20}/> Governance</h2></div>
  {govData.map(g=><Card key={g.body} className="bg-[#0f1923] border-[#1e2d3d]"><CardContent className="p-4"><div className="flex items-start justify-between mb-3"><div><h3 className="text-sm font-medium text-[#e8f0f8]">{g.body}</h3><div className="text-[11px] text-[#4a6a8a] mt-1">Chair: {g.chair} &middot; {g.members} members &middot; {g.frequency}</div></div><div className="text-right text-[10px] text-[#4a6a8a]"><div>Last: {g.lastMeeting}</div></div></div><div className="text-[10px] uppercase tracking-wider text-[#3a5a7a] mb-2">Recent Decisions</div>{g.decisions.map((d,i)=><div key={i} className="flex items-center gap-2 py-1.5 text-xs text-[#a8c8e0] border-b border-[#162535] last:border-0"><I.Check className="text-emerald-400 shrink-0"/>{d}</div>)}</CardContent></Card>)}</div>);}

function PredictView(){return(<div className="space-y-6 animate-in fade-in duration-300"><div><h2 className="text-lg font-semibold text-[#e8f0f8] flex items-center gap-2"><I.Brain size={20}/> Predictive Optimization</h2></div>
  {predictModels.map(m=><Card key={m.model} className="bg-[#0f1923] border-[#1e2d3d]"><CardContent className="p-4"><div className="flex items-center justify-between mb-3"><div><h3 className="text-sm font-medium text-[#e8f0f8]">{m.model}</h3><p className="text-[11px] text-[#4a6a8a] mt-1">{m.desc}</p></div><div className="flex gap-2"><Badge variant="outline" className={`text-[10px] ${m.status==="Active"?"border-emerald-500/30 text-emerald-400":"border-amber-500/30 text-amber-400"}`}>{m.status}</Badge><Badge variant="outline" className="text-[10px] border-[#2a4a6b] text-[#6b8aad]">{m.accuracy}</Badge></div></div>{m.predictions.map((p,i)=><div key={i} className="bg-[#0a1520] border border-[#162535] rounded-lg p-3 mb-2 last:mb-0"><div className="text-xs text-[#a8c8e0] mb-2">{p.p}</div><div className="flex items-center justify-between"><Badge variant="outline" className="text-[10px] border-amber-500/30 text-amber-400">{p.confidence}</Badge><span className="text-[10px] text-emerald-400 font-medium">{p.action}</span></div></div>)}</CardContent></Card>)}</div>);}

function DataView(){return(<div className="space-y-6 animate-in fade-in duration-300"><div><h2 className="text-lg font-semibold text-[#e8f0f8] flex items-center gap-2"><I.Layers size={20}/> Structured Data Aggregation</h2></div>
  <div className="grid grid-cols-2 gap-3"><div className="bg-[#0f1923] border border-[#1e2d3d] rounded-lg p-4 text-center"><div className="text-2xl font-semibold text-[#e8f0f8]">{dataAgg.sources.length}</div><div className="text-[10px] text-[#4a6a8a]">Data Sources</div></div><div className="bg-[#0f1923] border border-[#1e2d3d] rounded-lg p-4 text-center"><div className="text-2xl font-semibold text-emerald-400">{dataAgg.qualityScore}%</div><div className="text-[10px] text-[#4a6a8a]">Quality Score</div></div></div>
  {dataAgg.sources.map(s=><Card key={s.name} className="bg-[#0f1923] border-[#1e2d3d]"><CardContent className="p-4"><div className="flex items-center justify-between mb-2"><div className="flex items-center gap-2"><Dot s="on"/><h3 className="text-sm font-medium text-[#e8f0f8]">{s.name}</h3></div><div className="flex gap-2"><Badge variant="outline" className="text-[10px] border-[#2a4a6b] text-[#6b8aad]">{s.records}</Badge><Badge variant="outline" className="text-[10px] border-[#2a4a6b] text-[#6b8aad]">{s.refresh}</Badge></div></div><div className="flex items-center gap-3 mb-2"><span className="text-[10px] text-[#4a6a8a]">Quality:</span><Progress value={s.quality} className="h-1.5 bg-[#162535] flex-1"/><span className="text-xs font-mono text-[#6b8aad]">{s.quality}%</span></div><div className="flex flex-wrap gap-1.5">{s.fields.map(f=><Badge key={f} variant="outline" className="text-[10px] border-[#162535] text-[#4a6a8a]">{f}</Badge>)}</div></CardContent></Card>)}</div>);}

function ProjectsView(){return(<div className="space-y-6 animate-in fade-in duration-300"><div><h2 className="text-lg font-semibold text-[#e8f0f8]">Project Dashboard</h2></div>
  <Card className="bg-[#0f1923] border-[#1e2d3d]"><CardContent className="p-4 space-y-2">{projects.map(p=><DrillRow key={p.name} label={`${p.name} - ${p.progress}%`}><div className="grid grid-cols-2 md:grid-cols-4 gap-3"><div><span className="text-[#4a6a8a]">Owner: </span><span className="text-[#a8c8e0]">{p.owner}</span></div><div><span className="text-[#4a6a8a]">Status: </span><span className="text-[#a8c8e0]">{p.status}</span></div><div><span className="text-[#4a6a8a]">Due: </span><span className="text-[#a8c8e0]">{p.due}</span></div><div><span className="text-[#4a6a8a]">Priority: </span><span className={p.priority==="Critical"?"text-red-400":p.priority==="High"?"text-amber-400":"text-[#6b8aad]"}>{p.priority}</span></div></div><Progress value={p.progress} className="h-2 bg-[#162535] mt-2"/></DrillRow>)}</CardContent></Card></div>);}

/* ═══ APP SHELL ═══ */
export default function App(){
  const[sec,setSec]=useState<Section>("dash");const[agentOpen,setAgentOpen]=useState(false);const[time,setTime]=useState(new Date());
  useEffect(()=>{const t=setInterval(()=>setTime(new Date()),60000);return()=>clearInterval(t);},[]);
  const nav:{id:Section;label:string;icon:ReactNode}[]=[{id:"dash",label:"Dashboard",icon:<I.Bar/>},{id:"ops",label:"Operations",icon:<I.Activity/>},{id:"census",label:"Census & Migration",icon:<I.Map/>},{id:"reg",label:"Laws & Regulation",icon:<I.Shield/>},{id:"vendors",label:"Vendor Dashboard",icon:<I.Layers/>},{id:"modality",label:"Modality Routing",icon:<I.Route/>},{id:"cost",label:"Cost Modeling",icon:<I.Dollar/>},{id:"predict",label:"Predictive Analytics",icon:<I.Brain/>},{id:"stories",label:"Connect to Purpose",icon:<I.Heart/>},{id:"cases",label:"Case Studies",icon:<I.BookOpen/>},{id:"feedback",label:"Feedback Loops",icon:<I.Msg/>},{id:"gov",label:"Governance",icon:<I.Shield/>},{id:"data",label:"Data Aggregation",icon:<I.Layers/>},{id:"projects",label:"Projects",icon:<I.GitBranch/>}];

  return(<div className="min-h-screen bg-[#080e14] text-[#c8dff0]" style={{fontFamily:"'DM Sans',system-ui,sans-serif"}}><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&display=swap" rel="stylesheet"/>
    <header className="h-12 border-b border-[#1e2d3d] bg-[#0a1218]/80 backdrop-blur-lg flex items-center px-4 sticky top-0 z-50"><div className="flex items-center gap-3"><div className="w-7 h-7 rounded-md bg-gradient-to-br from-[#10b981] to-[#065f46] flex items-center justify-center"><I.Globe size={14} className="text-white"/></div><div><div className="text-sm font-semibold text-[#e8f0f8] leading-none">Language Services Hub</div><div className="text-[10px] text-[#4a6a8a] leading-none mt-0.5">Advocate Health &middot; AVP Emmanuel</div></div></div>
      <div className="ml-auto flex items-center gap-3"><span className="text-[10px] text-[#4a6a8a] font-mono hidden sm:block">{time.toLocaleDateString("en-US",{weekday:"short",month:"short",day:"numeric"})}</span><div className="flex items-center gap-1.5 hidden sm:flex"><Dot s="on"/><span className="text-[10px] text-emerald-400">6 Sources Online</span></div>
        <Dialog open={agentOpen} onOpenChange={setAgentOpen}><DialogTrigger asChild><Button size="sm" className="h-7 bg-[#0f3d2e] hover:bg-[#155e43] border border-[#1a7a56] text-xs gap-1.5"><I.Brain/> Agent</Button></DialogTrigger><DialogContent className="bg-[#0a1218] border-[#1e2d3d] text-[#c8dff0] max-w-2xl h-[75vh] p-0 flex flex-col"><AgentPanel/></DialogContent></Dialog></div></header>
    <div className="flex">
      <nav className="w-52 shrink-0 border-r border-[#1e2d3d] bg-[#0a1218]/50 min-h-[calc(100vh-48px)] sticky top-12 self-start hidden lg:block"><div className="p-2 space-y-0.5">{nav.map(n=><button key={n.id} onClick={()=>setSec(n.id)} className={`w-full flex items-center gap-2 px-3 py-1.5 rounded-md text-[11px] transition-all ${sec===n.id?"bg-[#0f2e22] text-emerald-300 border border-[#1a5a3e]":"text-[#6b8aad] hover:text-[#a8c8e0] hover:bg-[#0f1923] border border-transparent"}`}>{n.icon}<span>{n.label}</span></button>)}</div></nav>
      <div className="lg:hidden w-full sticky top-12 z-40 bg-[#0a1218] border-b border-[#1e2d3d] overflow-x-auto"><div className="flex p-2 gap-1">{nav.map(n=><button key={n.id} onClick={()=>setSec(n.id)} className={`flex items-center gap-1 px-2 py-1.5 rounded text-[10px] whitespace-nowrap ${sec===n.id?"bg-[#0f2e22] text-emerald-300 border border-[#1a5a3e]":"text-[#6b8aad] border border-transparent"}`}>{n.icon}{n.label}</button>)}</div></div>
      <main className="flex-1 p-4 md:p-6 max-w-[1100px]">
        {sec==="dash"&&<DashView/>}{sec==="ops"&&<OpsView/>}{sec==="census"&&<CensusView/>}{sec==="reg"&&<RegView/>}{sec==="vendors"&&<VendorView/>}{sec==="modality"&&<ModalityView/>}{sec==="cost"&&<CostView/>}{sec==="stories"&&<StoriesView/>}{sec==="cases"&&<CasesView/>}{sec==="feedback"&&<FeedbackView/>}{sec==="gov"&&<GovView/>}{sec==="predict"&&<PredictView/>}{sec==="data"&&<DataView/>}{sec==="projects"&&<ProjectsView/>}
      </main>
    </div></div>);
}
